# -*- coding: utf-8 -*-
"""TUGAS-9 Manipulasi dan Operasi List_HILMI MUFID_0046

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11g5nVE7N9ovAtizjq0yt3RyP5akYvYAz
"""

# TUGAS MANIPULASI DAN OPERASI LIST

print("=" * 60)
print("NOMOR 1")
print("=" * 60)

# Diberikan list
buah = ['apel', 'mangga', 'jeruk', 'anggur', 'pisang']
print(f"List awal buah = {buah}")
print()

# a. Tambahkan 'semangka' di akhir list
print("a. Tambahkan 'semangka' di akhir list")
buah.append('semangka')
print(f"   Hasil: {buah}")
print()

# b. Sisipkan 'durian' di antara 'jeruk' dan 'anggur'
print("b. Sisipkan 'durian' di antara 'jeruk' dan 'anggur'")
# Index 'jeruk' = 2, maka sisipkan di index 3 (setelah jeruk)
buah.insert(3, 'durian')
print(f"   Hasil: {buah}")
print()

# c. Hapus 'mangga' dari list
print("c. Hapus 'mangga' dari list")
buah.remove('mangga')
print(f"   Hasil: {buah}")
print()

# d. Ubah 'pisang' menjadi 'nanas'
print("d. Ubah 'pisang' menjadi 'nanas'")
# Cari posisi index 'pisang' kemudian ubah
index_pisang = buah.index('pisang')
buah[index_pisang] = 'nanas'
print(f"   Index pisang = {index_pisang}")
print(f"   Hasil: {buah}")
print()

# e. Tampilkan 3 buah pertama
print("e. Tampilkan 3 buah pertama")
tiga_buah_pertama = buah[:3]
print(f"   Hasil: {tiga_buah_pertama}")
print()

print("=" * 60)
print("NOMOR 2")
print("=" * 60)

# Diberikan list
angka = [45, 12, 78, 23, 56, 89, 34]
print(f"List awal angka = {angka}")
print()

# a. Urutkan list secara ascending
print("a. Urutkan list secara ascending")
angka_ascending = angka.copy()  # membuat salinan agar list asli tidak berubah
angka_ascending.sort()
print(f"   Hasil sort ascending: {angka_ascending}")
print()

# b. Urutkan list secara descending
print("b. Urutkan list secara descending")
angka_descending = angka.copy()  # membuat salinan
angka_descending.sort()
angka_descending.reverse()  # membalik list setelah di-sort
print(f"   Hasil sort descending: {angka_descending}")
print()